### ISSUE TITLE
GLua Optimization 

### ISSUE THREAD

**Issue by binbonn** [LastPlayerTR/AddonTracking#1]
hey bro maybe you can cache print function, because you called twice this function.

https://cdn.discordapp.com/attachments/1046147117678338210/1245766881676099784/images_90.jpg?ex=6659f251&is=6658a0d1&hm=cae82f5bd2aa9c46da5aa3b62695021ed45f0942345468919f8554b79f1a5e3d&
(şaka, last seviliyorsun ❤️)

**Comment by LastPlayerTR** [comment]
https://youtu.be/KDV_-rXGy7A?si=F00UyI8KkeckP7AH
Discord ver yavrum özledim seni

**Comment by binbonn** [comment]
binbontr 
eklersin oradan konuşur sohbet ederiz
